# Generated by Django 4.2.23 on 2025-09-10 17:39

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_add_graphqlquery_owner_content_type'),
        ('nautobot_golden_config', '0031_configcompliance_actual_config_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configcompliance',
            name='actual_config_hash',
        ),
        migrations.RemoveField(
            model_name='configcompliance',
            name='intended_config_hash',
        ),
        migrations.RemoveField(
            model_name='configcompliancehash',
            name='config_content',
        ),
        migrations.CreateModel(
            name='ConfigHashGrouping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('config_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('config_content', models.JSONField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_hash_groups', to='nautobot_golden_config.compliancerule')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['rule', 'config_hash'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='configcompliancehash',
            name='config_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash_records', to='nautobot_golden_config.confighashgrouping'),
        ),
        migrations.AddIndex(
            model_name='confighashgrouping',
            index=models.Index(fields=['rule', 'config_hash'], name='nautobot_go_rule_id_634624_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='confighashgrouping',
            unique_together={('rule', 'config_hash')},
        ),
    ]
