# Generated by Django on 2025-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0031_configcompliance_actual_config_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcompliancehash',
            name='config_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, help_text="SHA-256 hash of the configuration content"),
        ),
    ]